FROM nginx:latest
# SHELL ["/bin/ash", "-oeux", "pipefail", "-c"]

# ENV TZ=JST

# RUN apk update && \
#   apk add --update --no-cache --virtual=.build-dependencies g++

# COPY ./default.conf /etc/nginx/conf.d/default.conf